language: python
os: linux
sudo: false
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_cb4f75dafb00_key -iv $encrypted_cb4f75dafb00_iv
  -in SpartaHack-API-2019_dev.postman_environment.json.enc -out tests/SpartaHack-API-2019_dev.postman_environment.json
  -d
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install -r requirements.txt
- npm install newman
script:
- export FLASK_ENV=development
- export FLASK_APP=app.py
- flask run &
- APP_PID=$!
- node_modules/.bin/newman run tests/SpartaHack_API_2019_tests.postman_collection.json
  -e tests/SpartaHack-API-2019_dev.postman_environment.json
- kill $APP_PID
