language: python
os: linux
sudo: false

python:
  - "3.5"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install -r requirements.txt

script:
  - export FLASK_ENV=development
  - python app.py &
  - APP_PID=$!
  - newman run SpartaHack_API_2019.postman_collection.json/tests -e local\ env.postman_environment.json/tests
  - kill $APP_PID