language: python
os: linux
sudo: false
python:
- '3.5'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
#- sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
#- sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

install:
- pip install -r requirements.txt
- npm install newman
script:
- export FLASK_ENV=development
- export FLASK_APP=app.py
- flask run &
- APP_PID=$!
- node_modules/.bin/newman run tests/SpartaHack_API_2019_tests.postman_collection.json -e tests/SpartaHack-API-2019_dev.postman_environment.json
- kill $APP_PID
